name: OWASP ZAP Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "https://ciwiproject.wuaze.com/"
          cmd_options: "-r report_html.html"

      - name: Upload ZAP Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: report_html.html

      - name: Upload ZAP Report (Markdown)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: report_md.md

      - name: Upload ZAP Report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json
